### ISSUE TITLE
Images don't display until the HTML editor is clicked

### ISSUE THREAD

**Issue by lweber-d2l** [BrightspaceUI/htmleditor#274]
Environment: Quad; site version 20.21.8.31033. Chrome 91.0.4472.114
Description: 
* The Continuous Professional Development tool is an FRA.  
* In that tool, we have a dialog that uses htmleditor so users can answer questions related to personal development activities.
* After embedding an image and saving, when viewing the user's answer, the image does not display until the user clicks in the editor.  Example: 
![image-does-not-display-until editor-in-focus](https://user-images.githubusercontent.com/59580355/123296978-1e8ba680-d4e5-11eb-8879-05a76cd3db7d.gif)

**Comment by grant-cleary** [comment]
@lweber-d2l How is the image being embedded in this case? What URL does that image actually point to?

**Comment by lweber-d2l** [comment]
Hi @grant-cleary, the URL points to a file in Org Content, in this case `/content/this-is-fine-2.png`.

**Comment by grant-cleary** [comment]
Do you see any network errors when loading that HTML block?

**Comment by lweber-d2l** [comment]
I do: GET https://s.brightspace.com/content/this-is-fine-2.png 403
![403-get-image](https://user-images.githubusercontent.com/59580355/123299282-58f64300-d4e7-11eb-8a96-d317082dda33.png)

**Comment by grant-cleary** [comment]
Ok, so it looks like we're setting a relative path on the image source. This works okay in the editor because TinyMCE prepends any relative URLs with its internal host, but that wouldn't apply when the editor isn't open. That's fixable, but I also want to do a bit more testing because I'm not sure why this would only be happening in this FRA (not to say it doesn't happen in others; just that I haven't seen any issues raised).
